name: ticketing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI and asset management
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  app_links: ^6.4.1
  crypto: ^3.0.3 

  # State Management, DI, and Architecture
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  auto_route: ^9.2.2
  shared_preferences: ^2.5.3
  
  # Networking and Security
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^2.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.8.0
  mockito: ^5.4.4
  
  # Code Generators (dev_dependencies)
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcons (16)/playstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true